spring:
  application:
    name: batch

application:
  output-file: /home/dthibau/Formations/SpringBatch/MyWork/products-out.csv
---
spring:
  config:
    activate:
      on-profile:
        - prod

  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5434/spring-batch
    username: postgres
  batch:
    jdbc:
      initialize-schema: always