appli.source.directory=/home/dthibau/Formations/SpringBatch/MyWork/job/source
appli.input.jdbc=jdbc:mysql://localhost:3306/produits
appli.input.directory: /home/dthibau/Formations/SpringBatch/MyWork/job/input
appli.temp.directory=/home/dthibau/Formations/SpringBatch/MyWork/job/temp
appli.output.directory=/home/dthibau/Formations/SpringBatch/MyWork/job/output
  


