spring:
  application:
    name: batch
  batch:
    job:
      enabled: false

application:
  output-file: /home/dthibau/Formations/SpringBatch/MyWork/products-out.csv
  output-xml: /home/dthibau/Formations/SpringBatch/MyWork/products-out.xml
  input-bd: jdbc:postgresql://localhost:5434/produit

---
spring:
  config:
    activate:
      on-profile:
        - prod

  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5434/spring-batch
    username: postgres
  batch:
    jdbc:
      initialize-schema: always