spring:
  application:
    name: batch
  batch:
    job:
      enabled: false

application:
  input-bd: jdbc:postgresql://localhost:5434/produit
  source-directory: /home/dthibau/Formations/SpringBatch/MyWork/job/source
  input-directory: /home/dthibau/Formations/SpringBatch/MyWork/job/input
  temp-directory: /home/dthibau/Formations/SpringBatch/MyWork/job/temp
  output-directory: /home/dthibau/Formations/SpringBatch/MyWork/job/output
  output: jdbc:postgresql://localhost:5434/output-produits

---
spring:
  config:
    activate:
      on-profile:
        - prod

  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5434/spring-batch
    username: postgres
  batch:
    jdbc:
      initialize-schema: always